import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import { getActiveAppSession, isAppSessionBoundaryPending, ownerScopedUserDataPath } from '../appSessionState.js';
import { getCurrentDbClientSnapshot } from '../localDb/client/current.js';
import { ingestMedia } from '../cindy-media/ingest.js';
import { parseBlobUrl, resolveSafe } from '../cindy-media/blobStore.js';
import { removeRefs } from '../cindy-media/ledger.js';
import { captureMediaRefCompensationScope } from '../cindy-media/refCompensationJournal.js';
import { prepareWallpaperImage } from '../custom-wallpaper.js';
import type { GeneratedMedia } from './service.js';

/** New generated bytes use the owner ledger; old apply/ files remain readable. */
export async function storeCompanionMedia(
  media: GeneratedMedia,
  kind: 'still' | 'video',
  assertStillValid: () => void,
): Promise<string> {
  const owner = getActiveAppSession().dataOwnerId;
  const current = getCurrentDbClientSnapshot();
  if (!owner || isAppSessionBoundaryPending() || !current || current.userId !== owner)
    throw new Error('HOST_NOT_READY');
  const scope = captureMediaRefCompensationScope();
  const assertActive = () => {
    assertStillValid();
    scope.assertStillValid();
    if (getCurrentDbClientSnapshot() !== current) throw new Error('ACCOUNT_CHANGED');
  };
  assertActive();
  const buffer = kind === 'still' ? await prepareWallpaperImage(media.buffer) : media.buffer;
  assertActive();
  if (kind === 'video' && (
    media.mimeType !== 'video/mp4' || buffer.length > 100 * 1024 * 1024 ||
    buffer.subarray(4, 8).toString() !== 'ftyp'
  )) throw new Error('INVALID_VIDEO');
  const hash = createHash('sha256').update(buffer).digest('hex');
  const written = await ingestMedia({
    buffer,
    mimeType: kind === 'still' ? 'image/webp' : 'video/mp4',
    isCache: false,
    refs: [{ refKind: 'integration-cache', refId: 'desktop-companion:' + hash, originKind: 'integration', originId: 'desktop-companion' }],
    assertStillValid: assertActive,
    refCompensationScope: { ...scope, assertStillValid: assertActive },
  }, current.client.drizzle);
  return written.url;
}

export function companionMediaPath(source: string): string {
  if (parseBlobUrl(source)) return resolveSafe(source).absPath;
  const root = ownerScopedUserDataPath('desktop-companion', 'apply');
  // Legacy compatibility never accepts another owner's directory or a symlink.
  if (path.dirname(source) !== root || fs.realpathSync(source) !== source)
    throw new Error('INVALID_MEDIA');
  return source;
}

export function companionMediaExists(source: string): boolean {
  try {
    const stat = fs.lstatSync(companionMediaPath(source));
    return stat.isFile() && !stat.isSymbolicLink();
  } catch {
    return false;
  }
}

export async function releaseCompanionMedia(source: string): Promise<void> {
  const parsed = parseBlobUrl(source);
  if (parsed) {
    const current = getCurrentDbClientSnapshot();
    if (!current || isAppSessionBoundaryPending() || current.userId !== getActiveAppSession().dataOwnerId)
      throw new Error('HOST_NOT_READY');
    await removeRefs({ refKind: 'integration-cache', refId: 'desktop-companion:' + parsed.hash }, current.client.drizzle);
  } else {
    fs.rmSync(companionMediaPath(source));
  }
}
