/**
 * cindy-subagent —— 写进 pi `PI_CODING_AGENT_DIR/extensions/` 的扩展源码(字符串常量)。
 *
 * 为什么是 Cindy 自己的实现,而不是装社区包:
 *  - pi 上游刻意不内置子代理,社区(`pi-subagents` 等)一律以「扩展 + 子 pi 进程」补齐。
 *    但整包引入等于把第三方代码塞进 `pi-harness.md` §4.2 划定的自包含注入边界,并跟着上游
 *    版本跑。这里参考社区与上游示例的设计,只重做我们需要的部分,代码归 Cindy 所有。
 *  - 沿用 §3 设计原则:直接用 pi 自身能力(`--mode json` 子进程、`--tools` 白名单、
 *    `--append-system-prompt`),不再套一层外部框架、不做二次转义。
 *
 * 这段代码跑在 **pi 子进程**(bun runtime)里,不能 import cindy 任何模块;只依赖 pi 的
 * ExtensionAPI 与 node 内建。约束(与 cindy-bridge 同):模板里**不得出现模板字符串**,
 * 否则 `${...}` 会被外层 String.raw 插值 —— 一律用字符串拼接。
 *
 * 安全形态(重要,别当冗余删掉):
 *  - 子进程**继承 `PI_CODING_AGENT_DIR`**,因此同样加载 cindy-bridge → 权限门(`tool_call`
 *    拦截 + 凭证路径硬拦)对子代理照样生效。不传 `--no-extensions` 正是为了保住这条。
 *  - 第一期只给**只读**工具白名单(read/grep/find/ls)。这不只是保守:ask 档下非只读工具
 *    要走 `ctx.ui.confirm`,而 headless 子进程没有 UI 承接、bridge 的 catch 分支按 deny
 *    收口(fail-closed)。只读工具在门里直接放行,因此只读子代理开箱可用;写权限子代理需
 *    要先把子进程的确认请求转发到 Cindy 审批 UI,属独立一期。
 *  - `CINDY_PI_SUBAGENT_DEPTH` 防递归:达到上限后本扩展不注册工具,子代理无法再派子代理。
 *  - `--no-session`:子代理不写会话文件,不污染 Cindy 的会话 JSONL。
 *
 * 进度回传走 pi 工具原生的 `onUpdate` 流(→ `tool_execution_update`),由
 * `subagent-progress.ts` 翻成统一 `agent_task_update` → 与 Claude / Codex 共用
 * `AgentTaskCard`。不另开侧信道。
 *
 * 更新方式:PiAgent 每次 startSession 覆写该文件。
 */

/** 工具名 —— 与 `@cindy/maker-shared` 的 `PI_SUBAGENT_TOOL_NAME` 必须一致(卡片判据靠它)。 */
export const CINDY_SUBAGENT_TOOL_NAME = 'subagent';

export const CINDY_SUBAGENT_EXTENSION_FILENAME = 'cindy-subagent.ts';

/** Cindy 注入给子进程的 env 名:pi 二进制路径、递归深度、子代理模型。 */
export const CINDY_SUBAGENT_ENV = {
  binary: 'CINDY_PI_SUBAGENT_BINARY',
  depth: 'CINDY_PI_SUBAGENT_DEPTH',
  /**
   * 子代理运行期快照文件({model?, provider?})。刻意不用 env 传 model:env 在 spawn 时
   * 定型,会话中途 setModel 后子代理会继续用旧模型;provider 不一起传还会让同名模型落到
   * 错误 endpoint。扩展每次派子代理现读本文件(与权限档同机制)。
   */
  runtimeFile: 'CINDY_PI_SUBAGENT_RUNTIME_FILE',
} as const;

export const CINDY_SUBAGENT_EXTENSION_SOURCE = String.raw`/**
 * cindy-subagent (generated by Cindy — do not edit; overwritten on session start)
 */
import { spawn } from 'node:child_process';
import { readFileSync } from 'node:fs';

const TOOL_NAME = 'subagent';
const MARKER = '__cindySubagent';
const BINARY_ENV = 'CINDY_PI_SUBAGENT_BINARY';
const DEPTH_ENV = 'CINDY_PI_SUBAGENT_DEPTH';
const RUNTIME_FILE_ENV = 'CINDY_PI_SUBAGENT_RUNTIME_FILE';

// 子代理不得再派子代理:深度到顶就不注册工具(与 codex agents.max_depth 同语义)。
const MAX_DEPTH = 1;
const MAX_TASKS = 8;
const MAX_CONCURRENCY = 4;
// 回给父模型的单任务输出上限:子代理的价值是"只回结论",别把全文灌回主线程。
const MAX_OUTPUT_CHARS = 16000;
// 兜底超时:卡死的子代理不能把父 turn 永久挂住。
const TASK_TIMEOUT_MS = 10 * 60 * 1000;

// 只读画像。tools 同时是 --tools 白名单:非只读工具在 ask 档会被 bridge fail-closed
// 拒掉(headless 子进程没有确认 UI),所以第一期只给只读能力。
const PROFILES = {
  scout: {
    tools: 'read,grep,find,ls',
    prompt: 'You are a scout subagent. Investigate the codebase and answer the question you were given. '
      + 'Read only what you need. Report conclusions with file:line anchors — never paste long file contents. '
      + 'Be concise: the parent agent only needs your findings, not your process.',
  },
  reviewer: {
    tools: 'read,grep,find,ls',
    prompt: 'You are a code review subagent. Review what you were asked to review and report concrete, '
      + 'actionable defects with file:line anchors, most severe first. State the failure scenario for each. '
      + 'Do not restate what the code does. If you find nothing real, say so plainly.',
  },
  planner: {
    tools: 'read,grep,find,ls',
    prompt: 'You are a planning subagent. Read the relevant code, then produce a concrete implementation plan: '
      + 'which files change, in what order, and what could break. Cite file:line for every claim about current '
      + 'behavior. Do not write code.',
  },
};

function profileNames() {
  return Object.keys(PROFILES).join(' | ');
}

/**
 * 现读子代理运行期快照(model + provider)。每次派子代理都读 —— 会话中途 setModel 后
 * 立即生效。
 *
 * 读不到返回空对象,调用方**必须据此失败关闭**:退回 pi 默认解析会把 BYOM / 本地
 * provider 的请求发到错误 endpoint,那比"本次没有子代理"糟糕得多(review)。
 */
function readRuntimeSnapshot() {
  const file = process.env[RUNTIME_FILE_ENV];
  if (typeof file !== 'string' || file.length === 0) return {};
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf8'));
    if (!parsed || typeof parsed !== 'object') return {};
    const model = typeof parsed.model === 'string' && parsed.model.trim().length > 0
      ? parsed.model.trim()
      : undefined;
    const provider = typeof parsed.provider === 'string' && parsed.provider.trim().length > 0
      ? parsed.provider.trim()
      : undefined;
    return { model: model, provider: provider };
  } catch (err) {
    console.error('[cindy-subagent] runtime snapshot unreadable: ' + String(err));
    return {};
  }
}

function readDepth() {
  const raw = process.env[DEPTH_ENV];
  const parsed = typeof raw === 'string' ? Number.parseInt(raw, 10) : 0;
  return Number.isFinite(parsed) && parsed > 0 ? parsed : 0;
}

function clampText(text, max) {
  if (typeof text !== 'string') return '';
  const trimmed = text.trim();
  if (trimmed.length <= max) return trimmed;
  return trimmed.slice(0, max - 1) + '…';
}

/** 归一化入参成任务数组;抛出的错误直接回给模型(它能据此改调用)。 */
function normalizeTasks(params) {
  const input = params && typeof params === 'object' ? params : {};
  const raw = Array.isArray(input.tasks) && input.tasks.length > 0
    ? input.tasks
    : [{ agent: input.agent, task: input.task }];
  if (raw.length > MAX_TASKS) {
    throw new Error('subagent: at most ' + MAX_TASKS + ' tasks per call (got ' + raw.length + ')');
  }
  return raw.map(function (entry, index) {
    const item = entry && typeof entry === 'object' ? entry : {};
    const agent = typeof item.agent === 'string' ? item.agent.trim() : '';
    const task = typeof item.task === 'string' ? item.task.trim() : '';
    if (!Object.prototype.hasOwnProperty.call(PROFILES, agent)) {
      throw new Error('subagent: unknown agent "' + agent + '" (available: ' + profileNames() + ')');
    }
    if (!task) {
      throw new Error('subagent: task ' + (index + 1) + ' is missing a task description');
    }
    return { agent: agent, task: task };
  });
}

/** 逐行喂 JSONL:pi 的 --mode json 每行一个事件,chunk 边界可能切断一行。 */
function createLineReader(onLine) {
  let buffer = '';
  return function (chunk) {
    buffer += chunk;
    for (;;) {
      const newline = buffer.indexOf('\n');
      if (newline < 0) break;
      const line = buffer.slice(0, newline).trim();
      buffer = buffer.slice(newline + 1);
      if (line.length > 0) onLine(line);
    }
  };
}

function assistantTextOf(message) {
  if (!message || typeof message !== 'object') return '';
  const content = Array.isArray(message.content) ? message.content : [];
  const parts = [];
  for (const block of content) {
    if (block && typeof block === 'object' && block.type === 'text' && typeof block.text === 'string') {
      parts.push(block.text);
    }
  }
  return parts.join('');
}

function addUsage(totals, usage) {
  if (!usage || typeof usage !== 'object') return;
  const keys = ['input', 'output', 'cacheRead', 'cacheWrite'];
  for (const key of keys) {
    const value = usage[key];
    if (typeof value === 'number' && Number.isFinite(value) && value > 0) totals.tokens += value;
  }
}

/** 跑一个子代理,返回 { text, isError, toolUses, tokens }。 */
function runTask(binary, task, runtime, signal, onProgress) {
  return new Promise(function (resolve) {
    const profile = PROFILES[task.agent];
    const args = [
      '--mode', 'json',
      '--no-session',
      '--tools', profile.tools,
      '--append-system-prompt', profile.prompt,
    ];
    // provider 与 model 成对传:pi-harness §3 要求 BYOM / 本地模型直连对应原生 provider,
    // 只给 model 会让网关与 BYOM 同名模型落到默认 provider。
    if (runtime.provider) args.push('--provider', runtime.provider);
    if (runtime.model) args.push('--model', runtime.model);
    args.push(task.task);

    const childEnv = Object.assign({}, process.env);
    // 深度 +1:子代理进程里本扩展不再注册工具。
    childEnv[DEPTH_ENV] = String(readDepth() + 1);

    let child;
    try {
      child = spawn(binary, args, { cwd: process.cwd(), env: childEnv, stdio: ['ignore', 'pipe', 'pipe'] });
    } catch (err) {
      resolve({ text: 'subagent failed to start: ' + String(err), isError: true, toolUses: 0, tokens: 0 });
      return;
    }

    const totals = { tokens: 0 };
    let toolUses = 0;
    let finalText = '';
    let stderr = '';
    let settled = false;
    let timer = null;
    // 先声明:finish 在闭包里引用它,let 的 TDZ 不容许"定义在后、可能先被读"。
    let removeAbort = null;

    const finish = function (result) {
      if (settled) return;
      settled = true;
      if (timer) clearTimeout(timer);
      if (typeof removeAbort === 'function') removeAbort();
      resolve(result);
    };

    const kill = function () {
      try {
        child.kill('SIGTERM');
      } catch (err) {
        /* already gone */
      }
      // 宽限后强杀,避免僵尸子进程把 turn 挂住。
      setTimeout(function () {
        try {
          child.kill('SIGKILL');
        } catch (err) {
          /* already gone */
        }
      }, 2000);
    };

    const onAbort = function () {
      kill();
      finish({ text: 'subagent aborted by user.', isError: true, toolUses: toolUses, tokens: totals.tokens });
    };
    if (signal && typeof signal.addEventListener === 'function') {
      if (signal.aborted) {
        kill();
        finish({ text: 'subagent aborted by user.', isError: true, toolUses: 0, tokens: 0 });
        return;
      }
      signal.addEventListener('abort', onAbort, { once: true });
      removeAbort = function () {
        try {
          signal.removeEventListener('abort', onAbort);
        } catch (err) {
          /* ignore */
        }
      };
    }

    timer = setTimeout(function () {
      kill();
      finish({
        text: 'subagent timed out after ' + Math.round(TASK_TIMEOUT_MS / 1000) + 's.',
        isError: true,
        toolUses: toolUses,
        tokens: totals.tokens,
      });
    }, TASK_TIMEOUT_MS);
    if (timer && typeof timer.unref === 'function') timer.unref();

    const feed = createLineReader(function (line) {
      // 终态已上报后丢弃迟到输出:kill() 到 SIGKILL 之间有约 2 秒宽限,子进程仍可能吐
      // stdout;finish() 之后再回调 onProgress 会把已上报的 stopped/failed 重新写成
      // running(review)。这里在解析之前就短路,连 JSON.parse 都省掉。
      if (settled) return;
      let event;
      try {
        event = JSON.parse(line);
      } catch (err) {
        return;
      }
      if (!event || typeof event !== 'object') return;
      if (event.type === 'tool_execution_start') {
        toolUses += 1;
        onProgress({ toolUses: toolUses, tokens: totals.tokens });
        return;
      }
      if (event.type === 'message_end') {
        const message = event.message;
        if (message && message.role === 'assistant') {
          addUsage(totals, message.usage);
          const text = assistantTextOf(message);
          // 覆盖为最新一条有文本的 assistant 回复 = 子代理的结论。
          if (text.trim().length > 0) finalText = text;
          onProgress({ toolUses: toolUses, tokens: totals.tokens });
        }
      }
    });

    child.stdout.setEncoding('utf8');
    child.stdout.on('data', feed);
    child.stderr.setEncoding('utf8');
    child.stderr.on('data', function (chunk) {
      if (stderr.length < 4000) stderr += chunk;
    });
    child.on('error', function (err) {
      finish({ text: 'subagent process error: ' + String(err), isError: true, toolUses: toolUses, tokens: totals.tokens });
    });
    child.on('close', function (code) {
      const ok = code === 0;
      const body = finalText.trim().length > 0
        ? clampText(finalText, MAX_OUTPUT_CHARS)
        : (ok ? '(subagent produced no output)' : clampText(stderr, 2000) || ('subagent exited with code ' + String(code)));
      finish({ text: body, isError: !ok, toolUses: toolUses, tokens: totals.tokens });
    });
  });
}

export default async function cindySubagent(pi: any) {
  if (readDepth() >= MAX_DEPTH) return;
  const binary = process.env[BINARY_ENV];
  // 拿不到 pi 二进制路径就不注册:宁可没有这个工具,也不让模型调用一个必然失败的工具。
  if (typeof binary !== 'string' || binary.trim().length === 0) return;
  // host 未能持久化路由快照时会**不传**该 env → 本次会话完全不暴露子代理工具(fail-closed)。
  const runtimeFile = process.env[RUNTIME_FILE_ENV];
  if (typeof runtimeFile !== 'string' || runtimeFile.trim().length === 0) return;

  pi.registerTool({
    name: TOOL_NAME,
    label: 'Subagent',
    description: 'Delegate a focused, read-only investigation to a subagent running in its own context window. '
      + 'Use it for exploration whose intermediate output does not need to stay in this conversation: reading '
      + 'rule or design docs, surveying large or unfamiliar files, broad code searches, or getting an '
      + 'independent review. The subagent reports conclusions only. Available agents: ' + profileNames() + '. '
      + 'Pass {agent, task} for one, or {tasks:[{agent, task}, ...]} to run up to ' + MAX_TASKS + ' in parallel. '
      + 'Subagents are read-only (no bash, no file edits) and cannot spawn further subagents — do implementation '
      + 'and verification yourself.',
    parameters: {
      type: 'object',
      properties: {
        agent: { type: 'string', description: 'Agent profile: ' + profileNames() },
        task: {
          type: 'string',
          description: 'What to investigate. State exactly what to read and which question to answer.',
        },
        tasks: {
          type: 'array',
          description: 'Run several subagents in parallel (max ' + MAX_TASKS + ').',
          items: {
            type: 'object',
            properties: {
              agent: { type: 'string', description: 'Agent profile: ' + profileNames() },
              task: { type: 'string' },
            },
            required: ['agent', 'task'],
          },
        },
      },
      additionalProperties: false,
    },
    async execute(toolCallId: string, params: unknown, signal: AbortSignal, onUpdate: any) {
      const tasks = normalizeTasks(params);
      const runtime = readRuntimeSnapshot();
      // 使用点失败关闭:快照读不到(host 写失败后删除 / 目录只读 / 磁盘满)时拒绝派发,
      // 而不是不带 --provider/--model 让子进程走 pi 默认解析 —— 后者会把 BYOM / 本地
      // provider 的请求发到错误 endpoint。provider 恒由 host 写入,缺它即视为不可用。
      if (!runtime.provider) {
        throw new Error(
          'subagent is unavailable: Cindy could not read this session\'s model routing snapshot, '
          + 'so a subagent would run against the wrong provider. Tell the user; do the work yourself.',
        );
      }
      const startedAt = Date.now();
      const label = tasks.map(function (t) { return t.agent; }).join(', ');
      const taskId = String(toolCallId || 'subagent');
      const totals = { toolUses: 0, tokens: 0 };
      const perTask = tasks.map(function () { return { toolUses: 0, tokens: 0 }; });

      const report = function (status: string, summary?: string) {
        if (typeof onUpdate !== 'function') return;
        const details: Record<string, unknown> = {
          taskId: taskId,
          status: status,
          agentName: label,
          task: tasks.length === 1 ? tasks[0].task : tasks.length + ' parallel tasks',
          toolUses: totals.toolUses,
          totalTokens: totals.tokens,
          durationMs: Date.now() - startedAt,
        };
        details[MARKER] = 1;
        if (summary) details.summary = summary;
        if (runtime.model) details.model = runtime.model;
        try {
          onUpdate({ content: [{ type: 'text', text: status === 'running' ? 'Running subagent…' : status }], details: details });
        } catch (err) {
          /* progress is best-effort */
        }
      };

      const recompute = function () {
        let toolUses = 0;
        let tokens = 0;
        for (const entry of perTask) {
          toolUses += entry.toolUses;
          tokens += entry.tokens;
        }
        totals.toolUses = toolUses;
        totals.tokens = tokens;
      };

      report('running');

      const results: any[] = new Array(tasks.length);
      let next = 0;
      const worker = async function () {
        for (;;) {
          const index = next;
          next += 1;
          if (index >= tasks.length) return;
          results[index] = await runTask(binary, tasks[index], runtime, signal, function (progress: any) {
            perTask[index] = { toolUses: progress.toolUses, tokens: progress.tokens };
            recompute();
            report('running');
          });
          perTask[index] = { toolUses: results[index].toolUses, tokens: results[index].tokens };
          recompute();
          report('running');
        }
      };
      const lanes = Math.min(MAX_CONCURRENCY, tasks.length);
      const running = [];
      for (let i = 0; i < lanes; i += 1) running.push(worker());
      await Promise.all(running);

      const failed = results.filter(function (r) { return r && r.isError; }).length;
      const aborted = signal && signal.aborted === true;
      const sections = results.map(function (result, index) {
        const head = '## ' + tasks[index].agent + (result && result.isError ? ' (failed)' : '');
        return head + '\n' + (result ? result.text : '(no result)');
      });
      const text = sections.join('\n\n');
      // 任一子任务失败即整卡 failed:部分成功不足以把批次报成完成(greptile P1)。
      report(aborted ? 'stopped' : failed > 0 ? 'failed' : 'completed',
        failed > 0 ? failed + ' of ' + results.length + ' subagents failed' : undefined);

      if (failed === results.length && results.length > 0) {
        throw new Error(text);
      }
      return {
        content: [{ type: 'text', text: text }],
        details: {
          tasks: tasks.map(function (t, index) {
            return {
              agent: t.agent,
              task: t.task,
              isError: results[index] ? results[index].isError === true : true,
              toolUses: perTask[index].toolUses,
              tokens: perTask[index].tokens,
            };
          }),
        },
      };
    },
  });
}
`;
