/**
 * cindy-bridge —— 写进 pi agentHome/extensions/ 的扩展源码(字符串常量)。
 *
 * 这段代码跑在 **pi 子进程**(bun runtime)里,不能 import cindy 任何模块;
 * 只依赖 pi 的 ExtensionAPI、fetch 与 node:fs。职责:
 *  1. 权限门:tool_call 拦截。bypassPermissions 放行;ask 档下只读内置工具放行,
 *     其余(bash/edit/write + 全部桥接 MCP 工具)经 ctx.ui.confirm 走 cindy 审批
 *     (RPC 模式 → extension_ui_request → PiAgent → interactionResolver)。
 *     权限档从 CINDY_PI_PERMISSION_FILE 每次现读 —— setPermissionMode 热切换生效;
 *     读不到一律按 ask(fail-closed)。
 *  2. MCP 桥:CINDY_PI_MCP_BRIDGE(JSON {token, servers[{name,url}]})指向 host 的
 *     localhost streamable-HTTP MCP bridge;对每个 server 走 initialize →
 *     tools/list,把工具注册成 pi 工具(mcp__<server>__<tool>),execute 转发
 *     tools/call。
 *  3. 会话树:注册 Cindy 私有 command，把 RPC prompt 桥到 ctx.navigateTree。
 *
 * 协议说明(@modelcontextprotocol/sdk StreamableHTTPServerTransport):
 *  - POST 单条 JSON-RPC;Accept 必须同时含 application/json 与 text/event-stream;
 *  - initialize 响应头 mcp-session-id,后续请求回带;
 *  - 响应可能是 application/json 或 SSE(请求-响应模式下 server 发完即关流,
 *    text() 可整体读取后解析);notification 返回 202 空体。
 *
 * 更新方式:PiAgent 每次 startSession 覆写该文件;改这里 = 改下次会话的桥行为。
 */

import { SENSITIVE_CREDENTIAL_PATH_PATTERN_SPECS } from '../shared/sensitive-credential-paths.js';

export const CINDY_BRIDGE_EXTENSION_FILENAME = 'cindy-bridge.ts';

export const CINDY_BRIDGE_EXTENSION_SOURCE = String.raw`/**
 * cindy-bridge (generated by Cindy — do not edit; overwritten on session start)
 */
import { readFileSync, realpathSync } from 'node:fs';
import path from 'node:path';
import { createBashTool } from '@earendil-works/pi-coding-agent';

const PERMISSION_TITLE = 'cindy:permission';
const READONLY_BUILTINS = new Set(['read', 'grep', 'find', 'ls']);
const FILE_WRITE_BUILTINS = new Set(['edit', 'write']);

// Pi 的模型鉴权、localhost proxy 与 MCP bearer 需要留在父进程 env 供 runtime
// 按请求解析，但绝不能继承进 LLM 可调用的 bash 子进程。名单由 host 按本次会话
// 实际注入的动态 BYOM env 生成；permission file 同样隐藏，避免一次获批的 bash
// 通过改写权限档给后续工具永久提权。
const SECRET_ENV_NAMES = new Set<string>([
  'CINDY_PI_SECRET_ENV_NAMES',
  'CINDY_PI_PERMISSION_FILE',
  'PI_CODING_AGENT_DIR',
]);
try {
  const names = JSON.parse(process.env.CINDY_PI_SECRET_ENV_NAMES ?? '[]');
  if (Array.isArray(names)) {
    for (const name of names) {
      if (typeof name === 'string' && name.length > 0) SECRET_ENV_NAMES.add(name);
    }
  }
} catch {
  // host 生成的配置若损坏，仍至少隐藏名单变量与 permission file；权限门继续 fail closed。
}

function withoutPiSecrets(env: Record<string, string | undefined>): Record<string, string | undefined> {
  const clean = { ...env };
  for (const name of SECRET_ENV_NAMES) delete clean[name];
  return clean;
}

// 凭证/密钥路径特征由 maker-core 的单一来源生成。bridge 自包含、运行时不能 import，
// 但不再维护第二份手写名单，避免新增凭证目录时 Pi 静默漏拦。
const CREDENTIAL_PATH_PATTERNS = ${JSON.stringify(SENSITIVE_CREDENTIAL_PATH_PATTERN_SPECS)}
  .map(({ source, flags }) => new RegExp(source, flags));

// 递归扫全部字符串叶子(含数组 / 嵌套对象),深度上限防环/超大入参。工具入参把路径
// 放进 { paths: [...] } 或 { opts: { path } } 时也能命中,不止顶层 string 字段。
function touchesCredentialPath(input: unknown, depth = 0): boolean {
  if (depth > 6 || input == null) return false;
  if (typeof input === 'string') return CREDENTIAL_PATH_PATTERNS.some((re) => re.test(input));
  if (Array.isArray(input)) return input.some((v) => touchesCredentialPath(v, depth + 1));
  if (typeof input === 'object') {
    return Object.values(input as Record<string, unknown>).some((v) => touchesCredentialPath(v, depth + 1));
  }
  return false;
}

// 未解析的路径字符串命不中凭证特征,但工作区内的符号链接可指向 /proc/self/environ 等
// 敏感目标;path.resolve 不跟随链接,故 touchesCredentialPath 会漏判(greptile 报)。这里
// 对每个字符串叶子额外 realpathSync 跟随链接,用**解析后**的真实目标再匹配一次特征。
// realpathSync 对不存在/非路径字符串会抛,catch 即跳过(仍有原始字符串检查兜底)。
function resolvesToCredentialPath(input: unknown, depth = 0): boolean {
  if (depth > 6 || input == null) return false;
  if (typeof input === 'string') {
    if (!input) return false;
    try {
      const resolved = realpathSync(input);
      return CREDENTIAL_PATH_PATTERNS.some((re) => re.test(resolved));
    } catch {
      return false;
    }
  }
  if (Array.isArray(input)) return input.some((v) => resolvesToCredentialPath(v, depth + 1));
  if (typeof input === 'object') {
    return Object.values(input as Record<string, unknown>).some((v) => resolvesToCredentialPath(v, depth + 1));
  }
  return false;
}

// 从 bash 子进程读取任意进程的初始环境(/proc/<pid|self>/environ)是绕过密钥剥离的旁路:
// spawn 边界虽从子进程 env 删了 Cindy 私密变量,但父 pi 进程仍持有它们,同 UID 下
// cat /proc/PPID/environ 可直接取回代理 token / 网关 key / BYOM key(codex 报)。
// 无法从 JS 侧让 /proc 不可读,故在工具边界对这类命令一律硬拦(含 Full access)。
// 线程视图 /proc/<pid>/task/<tid>/environ(乃至其它中间段)与 /proc/<pid>/environ 等价可读,
// 同样拦。中间段允许含斜杠(旧正则用 [^/...]* 只认单段,漏了 task/<tid>,codex report),
// 与 readonly-builtin 硬拦所用的共享 SENSITIVE_CREDENTIAL_PATH 特征(/proc/[^斜杠空白]*/environ)
// 保持同等覆盖。注:命令文本匹配不是安全边界(变形/间接读取可绕过,详见 pi-harness.md 的
// Full access 契约),这里只是 defense-in-depth。
// (本文件是 String.raw 模板,注释里严禁反引号,否则会提前终结模板。)
const PROC_ENVIRON_READ_RE = /\/proc\/[^\s'"]*\/environ\b/i;
function commandReadsProcessEnviron(command: unknown): boolean {
  return typeof command === 'string' && PROC_ENVIRON_READ_RE.test(command);
}

function currentPermissionState(): {
  mode: 'ask' | 'bypassPermissions';
  readOnlyRoots: string[];
} {
  const file = process.env.CINDY_PI_PERMISSION_FILE ?? '';
  if (!file) return { mode: 'ask', readOnlyRoots: [] };
  try {
    const parsed = JSON.parse(readFileSync(file, 'utf8'));
    return {
      mode: parsed?.mode === 'bypassPermissions' ? 'bypassPermissions' : 'ask',
      readOnlyRoots: Array.isArray(parsed?.readOnlyRoots)
        ? parsed.readOnlyRoots.filter((root: unknown) => typeof root === 'string')
        : [],
    };
  } catch {
    return { mode: 'ask', readOnlyRoots: [] };
  }
}

function isInsideRoot(candidate: string, root: string): boolean {
  const target = path.resolve(candidate);
  const base = path.resolve(root);
  const rel = path.relative(base, target);
  return rel === '' || (!rel.startsWith('..' + path.sep) && rel !== '..' && !path.isAbsolute(rel));
}

// ── MCP streamable-HTTP 极简 client ─────────────────────────────────────────

interface McpServerRef {
  name: string;
  url: string;
}

class McpHttpClient {
  private nextId = 1;
  private sessionId: string | null = null;

  constructor(
    private readonly server: McpServerRef,
    private readonly token: string,
  ) {}

  private headers(): Record<string, string> {
    const h: Record<string, string> = {
      'content-type': 'application/json',
      accept: 'application/json, text/event-stream',
      authorization: 'Bearer ' + this.token,
    };
    if (this.sessionId) h['mcp-session-id'] = this.sessionId;
    return h;
  }

  private async post(body: unknown): Promise<Response> {
    const res = await fetch(this.server.url, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify(body),
    });
    const sid = res.headers.get('mcp-session-id');
    if (sid) this.sessionId = sid;
    return res;
  }

  /** 解析 application/json 或 SSE 响应体里 id 匹配的 JSON-RPC response。 */
  private async readResponse(res: Response, id: number): Promise<any> {
    const contentType = res.headers.get('content-type') ?? '';
    if (!res.ok) {
      const text = await res.text().catch(() => '');
      throw new Error('MCP HTTP ' + res.status + ': ' + text.slice(0, 300));
    }
    if (contentType.includes('text/event-stream')) {
      const text = await res.text();
      for (const chunk of text.split('\n\n')) {
        for (const line of chunk.split('\n')) {
          if (!line.startsWith('data:')) continue;
          try {
            const msg = JSON.parse(line.slice(5).trim());
            if (msg && msg.id === id && ('result' in msg || 'error' in msg)) return msg;
          } catch {
            /* keep scanning */
          }
        }
      }
      throw new Error('MCP SSE response missing id=' + id);
    }
    return res.json();
  }

  async request(method: string, params?: unknown): Promise<any> {
    const id = this.nextId++;
    const res = await this.post({ jsonrpc: '2.0', id, method, ...(params !== undefined ? { params } : {}) });
    const msg = await this.readResponse(res, id);
    if (msg.error) {
      throw new Error('MCP ' + method + ' failed: ' + (msg.error.message ?? JSON.stringify(msg.error)));
    }
    return msg.result;
  }

  async notify(method: string, params?: unknown): Promise<void> {
    await this.post({ jsonrpc: '2.0', method, ...(params !== undefined ? { params } : {}) }).catch(() => {});
  }

  async initialize(): Promise<void> {
    await this.request('initialize', {
      protocolVersion: '2025-03-26',
      capabilities: {},
      clientInfo: { name: 'cindy-pi-bridge', version: '1.0.0' },
    });
    await this.notify('notifications/initialized');
  }
}

function mcpContentToPi(content: unknown): Array<Record<string, unknown>> {
  const out: Array<Record<string, unknown>> = [];
  if (Array.isArray(content)) {
    for (const item of content) {
      if (!item || typeof item !== 'object') continue;
      const rec = item as Record<string, unknown>;
      if (rec.type === 'text' && typeof rec.text === 'string') {
        out.push({ type: 'text', text: rec.text });
      } else if (rec.type === 'image' && typeof rec.data === 'string') {
        out.push({ type: 'image', data: rec.data, mimeType: rec.mimeType ?? 'image/png' });
      } else {
        out.push({ type: 'text', text: JSON.stringify(rec) });
      }
    }
  }
  if (out.length === 0) out.push({ type: 'text', text: '(empty result)' });
  return out;
}

async function connectServer(pi: any, server: McpServerRef, token: string): Promise<number> {
  const client = new McpHttpClient(server, token);
  await client.initialize();
  const listed = await client.request('tools/list', {});
  const tools: any[] = Array.isArray(listed?.tools) ? listed.tools : [];
  for (const tool of tools) {
    const qualifiedName = 'mcp__' + server.name + '__' + tool.name;
    const parameters =
      tool.inputSchema && typeof tool.inputSchema === 'object'
        ? tool.inputSchema
        : { type: 'object', properties: {}, additionalProperties: true };
    try {
      pi.registerTool({
        name: qualifiedName,
        label: server.name + ': ' + tool.name,
        description: typeof tool.description === 'string' && tool.description.length > 0
          ? tool.description
          : 'MCP tool ' + tool.name + ' from ' + server.name,
        parameters,
        async execute(_toolCallId: string, params: unknown) {
          const result = await client.request('tools/call', {
            name: tool.name,
            arguments: params ?? {},
          });
          const content = mcpContentToPi(result?.content);
          if (result?.isError) {
            const text = content
              .map((c) => (typeof c.text === 'string' ? c.text : ''))
              .join('\n')
              .trim();
            throw new Error(text.length > 0 ? text : 'MCP tool ' + tool.name + ' failed');
          }
          return { content, details: result?.structuredContent ?? {} };
        },
      });
    } catch (err) {
      console.error('[cindy-bridge] register ' + qualifiedName + ' failed: ' + String(err));
    }
  }
  return tools.length;
}

export default async function cindyBridge(pi: any) {
  // 覆盖内置 bash：保持 Pi 原生执行/截断/取消语义，只在 spawn 边界剥离 Cindy
  // 私密变量。模型仍可正常发请求，但它执行的任意命令拿不到 proxy/MCP/BYOM 凭证。
  const bashTool = createBashTool(process.cwd(), {
    // PI_SESSION_FILE 会暴露 agentHome，继而让一次获批的 shell 定位并篡改
    // permission file；其余 PI_SESSION_* 元数据对完成编码任务也不是必需能力。
    exposeSessionEnvironment: false,
    spawnHook: ({ command, cwd, env }) => ({
      command,
      cwd,
      env: withoutPiSecrets(env),
    }),
  });
  pi.registerTool({
    ...bashTool,
    execute: async (id: string, params: unknown, signal: AbortSignal, onUpdate: unknown) =>
      bashTool.execute(id, params as any, signal, onUpdate as any),
  });

  // ── 原生会话树桥 ──────────────────────────────────────────────────────────
  // RPC 没有 navigate_tree command；ExtensionCommandContext 才暴露 navigateTree。
  // 参数用 percent-encoded JSON，避免 prompt 命令的空格/斜杠解析污染 payload。
  pi.registerCommand('cindy-branch-switch', {
    description: 'Cindy internal session branch navigation',
    handler: async (args: string, ctx: any) => {
      let payload: {
        entryId?: unknown;
        summarize?: unknown;
        customInstructions?: unknown;
        label?: unknown;
      };
      try {
        payload = JSON.parse(decodeURIComponent(args.trim()));
      } catch {
        throw new Error('Invalid Cindy branch payload');
      }
      if (typeof payload.entryId !== 'string' || payload.entryId.length === 0 || payload.entryId.length > 128) {
        throw new Error('Invalid Cindy branch entry id');
      }
      const customInstructions = typeof payload.customInstructions === 'string'
        ? payload.customInstructions.trim().slice(0, 4000)
        : undefined;
      const label = typeof payload.label === 'string'
        ? payload.label.trim().slice(0, 120)
        : undefined;
      await ctx.waitForIdle();
      await ctx.navigateTree(payload.entryId, {
        summarize: payload.summarize === true,
        ...(customInstructions ? { customInstructions } : {}),
        ...(label ? { label } : {}),
      });
    },
  });

  // ── 权限门 ────────────────────────────────────────────────────────────────
  pi.on('tool_call', async (event: any, ctx: any) => {
    const permission = currentPermissionState();
    // Extra Dirs 的结构化写工具永远禁止，即使 Full access 也不能把“只读引用”静默
    // 升级成写目录。bash 仍由 Cindy 审批/模型指令约束（Pi 暂无 OS sandbox API）。
    const targetPath = typeof event.input?.path === 'string' ? event.input.path : '';
    if (
      targetPath
      && FILE_WRITE_BUILTINS.has(event.toolName)
      && permission.readOnlyRoots.some((root) => isInsideRoot(targetPath, root))
    ) {
      return { block: true, reason: 'Cindy extra reference directories are read-only.' };
    }
    // bash 读取任意进程的初始环境(/proc/<pid|self>/environ)是绕过密钥剥离的旁路:
    // spawn 边界虽删了子进程 env 的私密变量,父 pi 进程仍持有,cat /proc/PPID/environ
    // 同 UID 直取代理 token / 网关 / BYOM key(codex 报)→ 一律硬拦,含 Full access。
    if (event.toolName === 'bash' && commandReadsProcessEnviron(event.input?.command)) {
      return { block: true, reason: 'Cindy blocks reading process environment (/proc/*/environ), even with Full access.' };
    }
    // 凭证/密钥路径的内置只读工具(read/grep/find/ls)在 Pi 父进程内执行,而父进程 env
    // 必须保留代理会话 token 与 BYOM keys($ENV 请求期解析、bridge client 使用)。Full
    // access 若放行 read /proc/self/environ 这类路径,模型可直接取 token 调回环代理,
    // 绕过审批盗刷当前会话额度(greptile 报)→ 即使 bypassPermissions 也硬拦。原始路径
    // 命不中时还要跟随符号链接:工作区内的 link 可指向敏感目标,realpath 后再判一次。
    const credentialRead = READONLY_BUILTINS.has(event.toolName)
      && (touchesCredentialPath(event.input) || resolvesToCredentialPath(event.input));
    if (credentialRead && permission.mode === 'bypassPermissions') {
      return { block: true, reason: 'Cindy blocks reading credential or key paths, even with Full access.' };
    }
    if (permission.mode === 'bypassPermissions') return;
    if (READONLY_BUILTINS.has(event.toolName) && !credentialRead) return;
    let approved = false;
    try {
      approved = await ctx.ui.confirm(
        PERMISSION_TITLE,
        JSON.stringify({ toolName: event.toolName, input: event.input ?? {} }),
      );
    } catch {
      approved = false;
    }
    if (!approved) {
      return { block: true, reason: 'User denied this tool call via Cindy.' };
    }
  });

  // ── MCP 桥 ────────────────────────────────────────────────────────────────
  const raw = process.env.CINDY_PI_MCP_BRIDGE;
  if (!raw) return;
  let cfg: { token?: string; servers?: McpServerRef[] };
  try {
    cfg = JSON.parse(raw);
  } catch {
    console.error('[cindy-bridge] invalid CINDY_PI_MCP_BRIDGE JSON');
    return;
  }
  const token = cfg.token ?? '';
  for (const server of cfg.servers ?? []) {
    try {
      const count = await connectServer(pi, server, token);
      console.error('[cindy-bridge] connected ' + server.name + ' (' + count + ' tools)');
    } catch (err) {
      console.error('[cindy-bridge] connect ' + server.name + ' failed: ' + String(err));
    }
  }
}
`;
