export const BINARY_DOWNLOAD_PROGRESS_CHANNELS = {
  BINARY_DOWNLOAD_PROGRESS: "binary-download-progress",
} as const;

export type BINARY_DOWNLOAD_PROGRESSChannel = typeof BINARY_DOWNLOAD_PROGRESS_CHANNELS[keyof typeof BINARY_DOWNLOAD_PROGRESS_CHANNELS];
