export const COMPUTER_DRIVER_UPDATE_PROGRESS_CHANNELS = {
  COMPUTER_DRIVER_UPDATE_PROGRESS: "computer-driver-update-progress",
} as const;

export type COMPUTER_DRIVER_UPDATE_PROGRESSChannel = typeof COMPUTER_DRIVER_UPDATE_PROGRESS_CHANNELS[keyof typeof COMPUTER_DRIVER_UPDATE_PROGRESS_CHANNELS];
