export const DEVICE_LINK_CHANNELS = {
  ACCESS_REVOKED: "device-link:access-revoked",
  CLOSE_LINK: "device-link:close-link",
  CONNECTION_ISSUE: "device-link:connection-issue",
  CONTACTS_SYNC: "device-link:contacts:sync:v1",
  CONTROL_TARGET_CHANGED: "device-link:control-target-changed",
  CONTROLLED_STATE: "device-link:controlled-state",
  DELETE_DEVICE: "device-link:delete-device",
  DISCONNECT_ALL: "device-link:disconnect-all",
  GET_STATE: "device-link:get-state",
  KEEP_AWAKE_CHANGED: "device-link:keep-awake-changed",
  INVOKE: "device-link:invoke",
  LIST_DEVICES: "device-link:list-devices",
  MEDIA_FETCH: "device-link:media:fetch",
  MIRROR_CACHE_CLEAR: "device-link:mirror-cache:clear",
  MIRROR_CACHE_MESSAGES_GET: "device-link:mirror-cache:messages:get",
  MIRROR_CACHE_MESSAGES_PUT: "device-link:mirror-cache:messages:put",
  MIRROR_CACHE_SESSION_LIST_GET: "device-link:mirror-cache:session-list:get",
  MIRROR_CACHE_SESSION_LIST_PUT: "device-link:mirror-cache:session-list:put",
  OPEN_LINK: "device-link:open-link",
  OWNERSHIP_CHANGED: "device-link:ownership-changed",
  PRESENCE_CHANGED: "device-link:presence-changed",
  RENAME_DEVICE: "device-link:rename-device",
  REMOTE_PUSH: "device-link:remote-push",
  RESPONSIVENESS_CHANGED: "device-link:responsiveness-changed",
  RESTORE: "device-link:restore",
  REVOKE: "device-link:revoke",
  SET_DEVICE_CONTROL_ENABLED: "device-link:set-device-control-enabled",
  SET_ENABLED: "device-link:set-enabled",
  SET_KEEP_AWAKE: "device-link:set-keep-awake",
  STATUS_CHANGED: "device-link:status-changed",
  SUBSCRIBE: "device-link:subscribe",
  TELEGRAM_SET_ONLINE: "device-link:telegram:set-online",
  TELEGRAM_STATUS: "device-link:telegram:status",
  TOPIC_SUBSCRIBE: "device-link:topic-subscribe",
  TOPIC_UNSUBSCRIBE: "device-link:topic-unsubscribe",
  TRANSPORT_ACK: "__cindy/device-link/transport-ack",
  UNSUBSCRIBE: "device-link:unsubscribe",
  VOICE_CREDENTIAL_SYNC: "device-link:voice:credential-sync",
  VOICE_DICTIONARY_SYNC_STATE: "device-link:voice:dictionary:sync-state",
  VOICE_DICTIONARY_LEARNING: "device-link:voice:dictionary-learning",
  VOICE_DICTIONARY_GET: "device-link:voice:dictionary:get",
  VOICE_TRANSCRIBE: "device-link:voice:transcribe",
} as const;

export type DEVICE_LINKChannel = typeof DEVICE_LINK_CHANNELS[keyof typeof DEVICE_LINK_CHANNELS];
