export const DEVICE_LINK_CHANNELS = {
  CLOSE_LINK: "device-link:close-link",
  DELETE_DEVICE: "device-link:delete-device",
  DISCONNECT_ALL: "device-link:disconnect-all",
  GET_STATE: "device-link:get-state",
  INVOKE: "device-link:invoke",
  LIST_DEVICES: "device-link:list-devices",
  MEDIA_FETCH: "device-link:media:fetch",
  MIRROR_CACHE_CLEAR: "device-link:mirror-cache:clear",
  MIRROR_CACHE_MESSAGES_GET: "device-link:mirror-cache:messages:get",
  MIRROR_CACHE_MESSAGES_PUT: "device-link:mirror-cache:messages:put",
  MIRROR_CACHE_SESSION_LIST_GET: "device-link:mirror-cache:session-list:get",
  MIRROR_CACHE_SESSION_LIST_PUT: "device-link:mirror-cache:session-list:put",
  OPEN_LINK: "device-link:open-link",
  RENAME_DEVICE: "device-link:rename-device",
  RESTORE: "device-link:restore",
  REVOKE: "device-link:revoke",
  SET_DEVICE_CONTROL_ENABLED: "device-link:set-device-control-enabled",
  SET_ENABLED: "device-link:set-enabled",
  SET_KEEP_AWAKE: "device-link:set-keep-awake",
  SUBSCRIBE: "device-link:subscribe",
  TELEGRAM_SET_ONLINE: "device-link:telegram:set-online",
  TELEGRAM_STATUS: "device-link:telegram:status",
  TOPIC_SUBSCRIBE: "device-link:topic-subscribe",
  TOPIC_UNSUBSCRIBE: "device-link:topic-unsubscribe",
  UNSUBSCRIBE: "device-link:unsubscribe",
  VOICE_CREDENTIAL_SYNC: "device-link:voice:credential-sync",
  VOICE_DICTIONARY_LEARNING: "device-link:voice:dictionary-learning",
  VOICE_DICTIONARY_GET: "device-link:voice:dictionary:get",
  VOICE_TRANSCRIBE: "device-link:voice:transcribe",
} as const;

export type DEVICE_LINKChannel = typeof DEVICE_LINK_CHANNELS[keyof typeof DEVICE_LINK_CHANNELS];
