export const GHOSTS_CHANNELS = {
  AT_RESOURCE_PROVIDERS_LIST: "ghosts:at-resource-providers:list",
  AT_RESOURCES_QUERY: "ghosts:at-resources:query",
  BUILTIN_STATUS: "ghosts:builtin-status",
  CARD_ACTION: "ghosts:card:action",
  CARD_GET: "ghosts:card:get",
  CARD_LIST_BY_SESSION: "ghosts:card:list-by-session",
  CARD_REPORT_HEIGHT: "ghosts:card:report-height",
  CHANGED: "ghosts:changed",
  CINDY_PREFS: "ghosts:cindy-prefs",
  CINDY_PREFS_SET: "ghosts:cindy-prefs:set",
  CLEAR_UNREAD: "ghosts:clear-unread",
  CONFIRM_RESOLVE: "ghosts:confirm:resolve",
  DEV_RUNTIME: "ghosts:dev-runtime",
  ERRAND_PREFS: "ghosts:errand-prefs",
  ERRAND_PREFS_SET: "ghosts:errand-prefs:set",
  EXPORT: "ghosts:export",
  INSPECT: "ghosts:inspect",
  INSTALL: "ghosts:install",
  INSTALL_REQUESTED: "ghosts:install-requested",
  LEGACY_RECOVERY_STATUS: "ghosts:legacy-recovery-status",
  LIST: "ghosts:list",
  MARK_USED: "ghosts:mark-used",
  PICK_FILE: "ghosts:pick-file",
  PROVISIONING: "ghosts:provisioning",
  RECENT_USAGE: "ghosts:recent-usage",
  RECENT_USAGE_CHANGED: "ghosts:recent-usage-changed",
  RELOAD: "ghosts:reload",
  RESOLVE_PANEL_MEDIA: "ghosts:resolve-panel-media",
  RESTORE_BUILTIN: "ghosts:restore-builtin",
  RETRY_LEGACY_RECOVERY: "ghosts:retry-legacy-recovery",
  RUNTIME_CHANGED: "ghosts:runtime-changed",
  RUNTIME_STATES: "ghosts:runtime-states",
  SESSION_FOCUSED: "ghosts:session-focused",
  SET_ENABLED: "ghosts:set-enabled",
  SETUP_STATUS: "ghosts:setup-status",
  TAKE_PENDING_INSTALL: "ghosts:take-pending-install",
  UNINSTALL: "ghosts:uninstall",
  UNREAD: "ghosts:unread",
  UPDATE: "ghosts:update",
  WORKDIR_PREFS: "ghosts:workdir-prefs",
  WORKDIR_PREFS_SET: "ghosts:workdir-prefs:set",
} as const;

export type GHOSTSChannel = typeof GHOSTS_CHANNELS[keyof typeof GHOSTS_CHANNELS];
