export const SKILLHUB_CHANNELS = {
  CANCEL_INSTALL: "skillhub:cancel-install",
  CANCEL_PUBLISH: "skillhub:cancel-publish",
  DELETE_PUBLISHED: "skillhub:delete-published",
  GET_FOLDER_HASH: "skillhub:get-folder-hash",
  GET_MY_DEPTS: "skillhub:get-my-depts",
  GET_PUBLISHED_FILES: "skillhub:get-published-files",
  GET_PUBLISHED_VISIBILITY: "skillhub:get-published-visibility",
  GET_SCAN_STATUS: "skillhub:get-scan-status",
  GET_SNAPSHOT_DIFF: "skillhub:get-snapshot-diff",
  GET_USAGE_DIAGNOSIS_CONTEXT: "skillhub:get-usage-diagnosis-context",
  GET_USAGE_SUMMARY: "skillhub:get-usage-summary",
  HAS_SNAPSHOT: "skillhub:has-snapshot",
  INFO: "skillhub:info",
  INSTALL: "skillhub:install",
  INSTALL_PROGRESS: "skillhub:install-progress",
  IMPORT_LOCAL: "skillhub:import-local",
  LIST_CATEGORIES: "skillhub:list-categories",
  LIST_CHILDREN: "skillhub:list-children",
  LIST_MARKET: "skillhub:list-market",
  LIST_PUBLISHED_VERSIONS: "skillhub:list-published-versions",
  LIST_USER_TEAMS: "skillhub:list-user-teams",
  PUBLISH: "skillhub:publish",
  PUBLISH_PROGRESS: "skillhub:publish-progress",
  PICK_LOCAL: "skillhub:pick-local",
  READ_PUBLISHED_FILE: "skillhub:read-published-file",
  READ_RAW: "skillhub:read-raw",
  READ_SIBLING_FILE: "skillhub:read-sibling-file",
  READ_SKILL: "skillhub:read-skill",
  RECONCILE_MINE_REGISTRY: "skillhub:reconcile-mine-registry",
  REGISTRY_GET_BY_NAME: "skillhub:registry:get-by-name",
  RENAME_LOCAL: "skillhub:rename-local",
  SCAN: "skillhub:scan",
  SET_PUBLISHED_VISIBILITY: "skillhub:set-published-visibility",
  START_SCAN_POLL: "skillhub:start-scan-poll",
  STOP_SCAN_POLL: "skillhub:stop-scan-poll",
  SYNC: "skillhub:sync",
  UNINSTALL: "skillhub:uninstall",
  UNPUBLISH_PUBLISHED: "skillhub:unpublish-published",
  UPDATE_PUBLISHED: "skillhub:update-published",
  USAGE_ANALYTICS_REFRESHED: "skillhub:usage-analytics-refreshed",
  VALIDATE_FRONTMATTER: "skillhub:validate-frontmatter",
  WRITE_FILE: "skillhub:write-file",
} as const;

export type SKILLHUBChannel = typeof SKILLHUB_CHANNELS[keyof typeof SKILLHUB_CHANNELS];
