export const UPDATE_MOVE_TO_APPLICATIONS_CHANNELS = {
  UPDATE_MOVE_TO_APPLICATIONS: "update-move-to-applications",
} as const;

export type UPDATE_MOVE_TO_APPLICATIONSChannel = typeof UPDATE_MOVE_TO_APPLICATIONS_CHANNELS[keyof typeof UPDATE_MOVE_TO_APPLICATIONS_CHANNELS];
