import type { DshCompositionOptions, DshCordisConfig } from './protocol.js';

type JsExpression = { readonly expression: string };
const js = (expression: string): JsExpression => ({ expression });

/** Builds the known-good dsh plugin graph; secrets intentionally stay in process env. */
export function buildDshCordisConfig(options: DshCompositionOptions): DshCordisConfig {
  if (options.provider !== 'deepseek-official') throw new Error(`dsh only supports provider deepseek-official (got ${options.provider})`);
  if (options.apiKeyEnv !== 'DEEPSEEK_API_KEY') throw new Error('dsh deepseek adapter requires DEEPSEEK_API_KEY');
  const reasoningEffort = options.thinkingPolicy ? undefined : (options.reasoningEffort ?? 'max');
  const thinking = options.thinkingPolicy === 'always-on'
    ? 'enabled'
    : options.thinkingPolicy === 'always-off' || reasoningEffort === 'off'
      ? 'disabled'
      : 'enabled';
  const deepseekConfig = {
    ...(options.baseUrl?.trim() ? { baseURL: options.baseUrl.trim() } : {}),
    thinking,
    ...(reasoningEffort ? { reasoningEffort } : {}),
    ...(options.models?.length
      ? {
          models: options.models.map((model) => ({
            id: model.id,
            ...(model.name?.trim() ? { name: model.name.trim() } : {}),
            ...(typeof model.contextWindow === 'number' && model.contextWindow > 0
              ? { contextWindow: model.contextWindow }
              : {}),
            ...(typeof model.maxTokens === 'number' && model.maxTokens > 0
              ? { maxTokens: model.maxTokens }
              : {}),
          })),
        }
      : {}),
  };
  const config: unknown[] = [
    { id: 'cindy-dsh-bridge', name: './cindy-dsh-bridge.mjs' },
    { id: 'llm-deepseek', name: '@deepseek-ai/dsh-llm-deepseek', config: deepseekConfig },
    { id: 'subprocess', name: '@deepseek-ai/dsh-subprocess-local' },
    ...(options.bashLocal !== false ? [{ id: 'bash', name: '@deepseek-ai/dsh-bash-local', config: { cwd: js('process.env.DSH_CWD ?? process.cwd()'), timeoutMs: 60000 } }] : []),
    { id: 'agent-spine', name: '@deepseek-ai/dsh-agent-spine-demo', config: { persona: js("process.env.DSH_SYSTEM_PROMPT ?? 'You are a coding agent.'"), workspaceContext: false, skills: { enabled: false }, toolBash: { enableRunInBackground: false }, toolJobs: false } },
    { id: 'sessions', name: '@deepseek-ai/dsh-session-persistence-jsonl', config: { root: js("process.env.DSH_SESSION_ROOT ?? './.sessions'"), compression: js("process.env.DSH_SNAPSHOT === undefined ? 'zstd' : 'none'") } },
    { id: 'session-checkpoints', name: '@deepseek-ai/dsh-session-checkpoint-policy' },
    { id: 'subagent', name: '@deepseek-ai/dsh-subagent' },
    { id: 'subagent-spawn-in-process', name: '@deepseek-ai/dsh-subagent-spawn-in-process', config: { providerName: 'spawn' } },
    { id: 'tool-subagent', name: '@deepseek-ai/dsh-tool-subagent', config: { provider: 'spawn', toolName: 'subagent', enableRunInBackground: false } },
    { id: 'tool-todo', name: '@deepseek-ai/dsh-tool-todo', config: { allowParallelInProgress: true } },
    { id: 'fs-local', name: '@deepseek-ai/dsh-fs-local', config: { cwd: js('process.env.DSH_CWD ?? process.cwd()') } },
    { id: 'fs-observation-policy', name: '@deepseek-ai/dsh-fs-observation-policy' },
    { id: 'tool-fs', name: '@deepseek-ai/dsh-tool-fs' },
    { id: 'token-meter', name: '@deepseek-ai/dsh-token-meter' },
    { id: 'compaction-basic', name: '@deepseek-ai/dsh-compaction-basic', config: { thresholdRatio: 0.8, retainRatio: 0.16, maxTokens: 8192, compactionRetries: 1 } },
  ];
  // DshCordisConfig's index signature models individual YAML nodes; the root is a list.
  return config as unknown as DshCordisConfig;
}

/** Minimal serializer for the dsh config subset; `!!js` expressions remain executable YAML tags. */
export function renderDshCordisYaml(config: DshCordisConfig): string {
  if (!Array.isArray(config)) throw new Error('dsh cordis config must be a plugin list');
  const render = (value: unknown, depth: number): string[] => {
    const pad = '  '.repeat(depth);
    if (Array.isArray(value)) return value.flatMap((item) => {
      if (isScalar(item)) return [`${pad}- ${scalar(item)}`];
      const entries = Object.entries(item as Record<string, unknown>);
      if (!entries.length) return [`${pad}- {}`];
      const [first, ...rest] = entries;
      return [`${pad}- ${first[0]}: ${isScalar(first[1]) ? scalar(first[1]) : ''}`, ...(isScalar(first[1]) ? [] : render(first[1], depth + 2)), ...rest.flatMap(([key, child]) => isScalar(child) ? [`${pad}  ${key}: ${scalar(child)}`] : [`${pad}  ${key}:`, ...render(child, depth + 2)])];
    });
    return Object.entries(value as Record<string, unknown>).flatMap(([key, child]) => isScalar(child) ? [`${pad}${key}: ${scalar(child)}`] : [`${pad}${key}:`, ...render(child, depth + 1)]);
  };
  return ['# Generated by Cindy for the dsh JSON-RPC runtime.', '# stdout is reserved for JSON-RPC; do not add a console logger or terminal UI.', ...render(config, 0), ''].join('\n');
}
function isJs(value: unknown): value is JsExpression { return typeof value === 'object' && value !== null && 'expression' in value; }
function isScalar(value: unknown): boolean { return value === null || ['string', 'number', 'boolean'].includes(typeof value) || isJs(value); }
function scalar(value: unknown): string {
  // YAML parses `:` and `?` in an unquoted expression as structure, not code.
  if (isJs(value)) return `!!js ${JSON.stringify(value.expression)}`;
  if (value === null) return 'null'; if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  // Package names beginning with `@` are YAML reserved indicators, so the
  // renderer must not emit any string as a plain scalar. JSON string syntax is
  // valid YAML and also protects future plugin ids from YAML's other implicit
  // scalar conversions.
  return JSON.stringify(String(value));
}
